# FILE IDENTIFICATION
# 
#  Name:         Makefile.msvc
#  Purpose:      Makefile for the CLSQL UFFI helper package (MSVC)
#  Programer:    Kevin M. Rosenberg
#  Date Started: Mar 2002
#
# This file, part of CLSQL, is Copyright (c) 2002-2010 by Kevin M. Rosenberg
#

BASE=c-test-fns

# Nothing to configure beyond here

SRC=$(BASE).c
OBJ=$(BASE).obj
DLL=$(BASE).dll

$(DLL): $(SRC)
	cl /MD /LD -D_MT /DWIN32=1 $(SRC)
        del $(OBJ) $(BASE).exp

clean:
        del /q $(DLL)


